# Variables for the host fredocloude
# This file is encrypted with ansible-vault

# The hostname of the host
hostname: fredocloude

# The timezone of the host
timezone: Europe/Paris

# The NFS directories to create
nfs_dirs:
  - /var/nfs

# The samba users
samba_users:
  - fredericbarrau
