# Variables for the host pihole
# This file is encrypted with ansible-vault

# The hostname of the host
hostname: pihole

# The timezone of the host
timezone: Europe/Paris

pihole_password:  !vault |
          $ANSIBLE_VAULT;1.1;AES256
          32636532326536653365396266373633386130336162633765383066313566363866393537343462
          3537393861333534636565663230653033666334376261660a643635323030383862373864316664
          32313436613964313663303234353731316566386133303232643862326664396239356466313536
          3063346139373238640a666437373966343464613963373733306436323961393761333065326530
          6236